DEBUG = FALSE
USE_MPI  = FALSE
USE_OMP  = FALSE
COMP = gnu
#DIM = 3
BL_NO_FORT = TRUE
USE_CUDA  = FALSE
USE_SYCL  = FALSE
USE_HIP   = FALSE

TINY_PROFILE = FALSE

AMREX_HOME = ../amrex
include $(AMREX_HOME)/Tools/GNUMake/Make.defs
include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package
include $(AMREX_HOME)/Tools/GNUMake/Make.rules





